version: "2.3"
services:
 nginx:
   build: .
   environment:
   - NGINX_UPSTEAM=http://debug:80
   - NGINX_TEMPLATE=auth-proxy
   - NGINX_RELOAD_INTERVAL=5s
   ports:
   - "8080:80"
   links:
   - debug
 debug:
   image: mendhak/http-https-echo
   logging: 
     driver: none